# Generated by Django 5.2.7 on 2025-10-27 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('CNPJ', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=15)),
                ('rua', models.CharField(max_length=255)),
                ('numero_casa', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='processo_administrativo',
            fields=[
                ('protocolo', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('FE', 'Está na fila de espera'), ('V', 'À ser vistoriado'), ('A', 'Em análise'), ('C', 'Concluído'), ('Ar', 'Arquivado')], max_length=20)),
                ('rua', models.CharField(max_length=255)),
                ('numero_casa', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('1 - Licenciamento', 'Licenciamento'), ('2 - Denúncia ', 'Denúncia')], max_length=20)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
